// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.2
// source: api/grpc/proto/market.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MarketService_GetMarketSummaries_FullMethodName  = "/market.v1.MarketService/GetMarketSummaries"
	MarketService_GetMarketSummary_FullMethodName    = "/market.v1.MarketService/GetMarketSummary"
	MarketService_GetPriceHistory_FullMethodName     = "/market.v1.MarketService/GetPriceHistory"
	MarketService_StreamMarketUpdates_FullMethodName = "/market.v1.MarketService/StreamMarketUpdates"
)

// MarketServiceClient is the client API for MarketService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MarketServiceClient interface {
	GetMarketSummaries(ctx context.Context, in *GetMarketSummariesRequest, opts ...grpc.CallOption) (*GetMarketSummariesResponse, error)
	GetMarketSummary(ctx context.Context, in *GetMarketSummaryRequest, opts ...grpc.CallOption) (*MarketSummary, error)
	GetPriceHistory(ctx context.Context, in *GetPriceHistoryRequest, opts ...grpc.CallOption) (*GetPriceHistoryResponse, error)
	StreamMarketUpdates(ctx context.Context, in *StreamMarketUpdatesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MarketSummary], error)
}

type marketServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMarketServiceClient(cc grpc.ClientConnInterface) MarketServiceClient {
	return &marketServiceClient{cc}
}

func (c *marketServiceClient) GetMarketSummaries(ctx context.Context, in *GetMarketSummariesRequest, opts ...grpc.CallOption) (*GetMarketSummariesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMarketSummariesResponse)
	err := c.cc.Invoke(ctx, MarketService_GetMarketSummaries_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketServiceClient) GetMarketSummary(ctx context.Context, in *GetMarketSummaryRequest, opts ...grpc.CallOption) (*MarketSummary, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MarketSummary)
	err := c.cc.Invoke(ctx, MarketService_GetMarketSummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketServiceClient) GetPriceHistory(ctx context.Context, in *GetPriceHistoryRequest, opts ...grpc.CallOption) (*GetPriceHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPriceHistoryResponse)
	err := c.cc.Invoke(ctx, MarketService_GetPriceHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketServiceClient) StreamMarketUpdates(ctx context.Context, in *StreamMarketUpdatesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MarketSummary], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MarketService_ServiceDesc.Streams[0], MarketService_StreamMarketUpdates_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamMarketUpdatesRequest, MarketSummary]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MarketService_StreamMarketUpdatesClient = grpc.ServerStreamingClient[MarketSummary]

// MarketServiceServer is the server API for MarketService service.
// All implementations must embed UnimplementedMarketServiceServer
// for forward compatibility.
type MarketServiceServer interface {
	GetMarketSummaries(context.Context, *GetMarketSummariesRequest) (*GetMarketSummariesResponse, error)
	GetMarketSummary(context.Context, *GetMarketSummaryRequest) (*MarketSummary, error)
	GetPriceHistory(context.Context, *GetPriceHistoryRequest) (*GetPriceHistoryResponse, error)
	StreamMarketUpdates(*StreamMarketUpdatesRequest, grpc.ServerStreamingServer[MarketSummary]) error
	mustEmbedUnimplementedMarketServiceServer()
}

// UnimplementedMarketServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMarketServiceServer struct{}

func (UnimplementedMarketServiceServer) GetMarketSummaries(context.Context, *GetMarketSummariesRequest) (*GetMarketSummariesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMarketSummaries not implemented")
}
func (UnimplementedMarketServiceServer) GetMarketSummary(context.Context, *GetMarketSummaryRequest) (*MarketSummary, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMarketSummary not implemented")
}
func (UnimplementedMarketServiceServer) GetPriceHistory(context.Context, *GetPriceHistoryRequest) (*GetPriceHistoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPriceHistory not implemented")
}
func (UnimplementedMarketServiceServer) StreamMarketUpdates(*StreamMarketUpdatesRequest, grpc.ServerStreamingServer[MarketSummary]) error {
	return status.Errorf(codes.Unimplemented, "method StreamMarketUpdates not implemented")
}
func (UnimplementedMarketServiceServer) mustEmbedUnimplementedMarketServiceServer() {}
func (UnimplementedMarketServiceServer) testEmbeddedByValue()                       {}

// UnsafeMarketServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MarketServiceServer will
// result in compilation errors.
type UnsafeMarketServiceServer interface {
	mustEmbedUnimplementedMarketServiceServer()
}

func RegisterMarketServiceServer(s grpc.ServiceRegistrar, srv MarketServiceServer) {
	// If the following call pancis, it indicates UnimplementedMarketServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MarketService_ServiceDesc, srv)
}

func _MarketService_GetMarketSummaries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMarketSummariesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketServiceServer).GetMarketSummaries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarketService_GetMarketSummaries_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketServiceServer).GetMarketSummaries(ctx, req.(*GetMarketSummariesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketService_GetMarketSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMarketSummaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketServiceServer).GetMarketSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarketService_GetMarketSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketServiceServer).GetMarketSummary(ctx, req.(*GetMarketSummaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketService_GetPriceHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPriceHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketServiceServer).GetPriceHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarketService_GetPriceHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketServiceServer).GetPriceHistory(ctx, req.(*GetPriceHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketService_StreamMarketUpdates_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamMarketUpdatesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MarketServiceServer).StreamMarketUpdates(m, &grpc.GenericServerStream[StreamMarketUpdatesRequest, MarketSummary]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MarketService_StreamMarketUpdatesServer = grpc.ServerStreamingServer[MarketSummary]

// MarketService_ServiceDesc is the grpc.ServiceDesc for MarketService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MarketService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "market.v1.MarketService",
	HandlerType: (*MarketServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMarketSummaries",
			Handler:    _MarketService_GetMarketSummaries_Handler,
		},
		{
			MethodName: "GetMarketSummary",
			Handler:    _MarketService_GetMarketSummary_Handler,
		},
		{
			MethodName: "GetPriceHistory",
			Handler:    _MarketService_GetPriceHistory_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamMarketUpdates",
			Handler:       _MarketService_StreamMarketUpdates_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/grpc/proto/market.proto",
}
