// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

type MarketSummary struct {
	CoinID         string        `json:"coinId"`
	Symbol         string        `json:"symbol"`
	Name           string        `json:"name"`
	CurrentPrice   float64       `json:"currentPrice"`
	MarketCap      *float64      `json:"marketCap,omitempty"`
	Volume24h      *float64      `json:"volume24h,omitempty"`
	PriceChange24h *float64      `json:"priceChange24h,omitempty"`
	LastUpdated    string        `json:"lastUpdated"`
	PriceHistory   []*PricePoint `json:"priceHistory"`
}

type PricePoint struct {
	Price      float64 `json:"price"`
	RecordedAt string  `json:"recordedAt"`
}

type Query struct {
}

type Subscription struct {
}
