package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
	"time"

	"github.com/holdex/epic-fermi/internal/domain/market"
)

// PriceHistory is the resolver for the priceHistory field.
func (r *marketSummaryResolver) PriceHistory(ctx context.Context, obj *MarketSummary, limit *int) ([]*PricePoint, error) {
	l := 100
	if limit != nil {
		l = *limit
	}
	dl := ForContext(ctx)
	if dl == nil {
		// Fallback to direct query if dataloader is not injected
		history, err := r.QueryService.GetPriceHistory(ctx, obj.CoinID, l)
		if err != nil {
			return nil, err
		}
		var points []*PricePoint
		for _, p := range history {
			points = append(points, &PricePoint{
				Price:      p.Price,
				RecordedAt: p.RecordedAt.Format(time.RFC3339),
			})
		}
		return points, nil
	}
	return dl.Load(ctx, obj.CoinID, l)
}

// MarketSummaries is the resolver for the marketSummaries field.
func (r *queryResolver) MarketSummaries(ctx context.Context, limit *int, offset *int) ([]*MarketSummary, error) {
	l := 100
	o := 0
	if limit != nil {
		l = *limit
	}
	if offset != nil {
		o = *offset
	}

	summaries, err := r.QueryService.GetMarketSummaries(ctx, l, o)
	if err != nil {
		return nil, err
	}

	result := make([]*MarketSummary, len(summaries))
	for i, s := range summaries {
		// Create local copies of values to take addresses
		mc := s.MarketCap
		vol := s.Volume24h
		pc := s.PriceChange24h

		result[i] = &MarketSummary{
			CoinID:         s.CoinID,
			Symbol:         s.Symbol,
			Name:           s.Name,
			CurrentPrice:   s.CurrentPrice,
			MarketCap:      &mc,
			Volume24h:      &vol,
			PriceChange24h: &pc,
			LastUpdated:    s.LastUpdated.Format(time.RFC3339),
		}
	}
	return result, nil
}

// MarketSummary is the resolver for the marketSummary field.
func (r *queryResolver) MarketSummary(ctx context.Context, coinID string) (*MarketSummary, error) {
	s, err := r.QueryService.GetMarketSummary(ctx, coinID)
	if err != nil {
		return nil, err
	}

	mc := s.MarketCap
	vol := s.Volume24h
	pc := s.PriceChange24h

	return &MarketSummary{
		CoinID:         s.CoinID,
		Symbol:         s.Symbol,
		Name:           s.Name,
		CurrentPrice:   s.CurrentPrice,
		MarketCap:      &mc,
		Volume24h:      &vol,
		PriceChange24h: &pc,
		LastUpdated:    s.LastUpdated.Format(time.RFC3339),
	}, nil
}

// PriceHistory is the resolver for the priceHistory field.
func (r *queryResolver) PriceHistory(ctx context.Context, coinID string, limit *int) ([]*PricePoint, error) {
	l := 100
	if limit != nil {
		l = *limit
	}

	history, err := r.QueryService.GetPriceHistory(ctx, coinID, l)
	if err != nil {
		return nil, err
	}

	result := make([]*PricePoint, len(history))
	for i, p := range history {
		result[i] = &PricePoint{
			Price:      p.Price,
			RecordedAt: p.RecordedAt.Format(time.RFC3339),
		}
	}
	return result, nil
}

// MarketPriceUpdated is the resolver for the marketPriceUpdated field.
func (r *subscriptionResolver) MarketPriceUpdated(ctx context.Context, coinID *string) (<-chan *MarketSummary, error) {
	ch := make(chan *MarketSummary, 1)

	eventsChan, err := r.EventStore.Subscribe(ctx, market.NewDataFetchedEvent)
	if err != nil {
		return nil, err
	}

	go func() {
		defer close(ch)
		for {
			select {
			case <-ctx.Done():
				return
			case ev, ok := <-eventsChan:
				if !ok {
					return
				}

				if me, ok := ev.(market.MarketEvent); ok {
					if coinID != nil && *coinID != me.Payload.CoinID {
						continue
					}

					mc := me.Payload.MarketCap
					vol := me.Payload.Volume24h
					pc := me.Payload.PriceChange24h

					summary := &MarketSummary{
						CoinID:         me.Payload.CoinID,
						Symbol:         me.Payload.Symbol,
						Name:           me.Payload.Name,
						CurrentPrice:   me.Payload.CurrentPrice,
						MarketCap:      &mc,
						Volume24h:      &vol,
						PriceChange24h: &pc,
						LastUpdated:    me.Payload.LastUpdated.Format(time.RFC3339),
					}

					select {
					case <-ctx.Done():
						return
					case ch <- summary:
					}
				}
			}
		}
	}()

	return ch, nil
}

// MarketSummary returns MarketSummaryResolver implementation.
func (r *Resolver) MarketSummary() MarketSummaryResolver { return &marketSummaryResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type (
	marketSummaryResolver struct{ *Resolver }
	queryResolver         struct{ *Resolver }
	subscriptionResolver  struct{ *Resolver }
)
